### ISSUE TITLE
What is $$ >> (context)

### ISSUE THREAD

**Issue by NarHakobyan** [modulovalue/flutter_beat_sequencer#1]
Hi, I just saw your interesting projects, and found `$$ >> (context)` and `>` syntax, can you please explain what are thet?

**Comment by modulovalue** [comment]
I'm using a custom RX implementation with flutter_hooks to remove a lot of boilerplate code. $, $$, $$$ are helpers related to flutter_hooks.

but in a nutshell:
```dart
/// Creates a new HookWidget (same as using a HookBuilder)
$$ >> (context) {
...
}

/// Subscribes and automatically disposes a wave (you can think of a wave as an Observable or a Stream)
$(() => ...);


/// Subscribes and automatically disposes a bloc.
$$$(() => ...);
```


The second part is a little hard to explain. 

Imagine you had to do math like this:
```dart
+(
  value:2
  child: +(
    child: + ()...
```

you can think of the `&` as a plus sign that combines widgets that accept a single child (I call them Applicators)

Because Applicators themselves are not widgets and will always need a child to become a Widget (remember, every widget tree has a last widget e.g. Text or a Container without a child) they need a last stage where they receive a real widget. that's what `>` is for.

I'm also using this concept for lists and other types because dart is a little limiting in that regard 

```bgColor(...) & height(..) > onListView() >> []```

The operators have been chosen in a way that you usually don't need any parentheses like in (3+2*2 = 7 and not 10)

This opens up a whole new world of possibilities.

you can apply applicators to each element of a list

```padding(all: 4.0) * []```

you can hide applicators

```padding(all: 4.0).when(false)```

...

dartfmt doesn't play well with that way of writing widgets so I recommend you to use the IntelliJ formatting.

There's really a lot more to explain but I hope this gives you a starting point.

**Comment by NarHakobyan** [comment]
thanks, I like your solution, it's amazing 👍

**Comment by NarHakobyan** [comment]
@modulovalue is there any tools to easily create dart package like bird_flutter?

**Comment by modulovalue** [comment]
> @modulovalue is there any tools to easily create dart package like bird_flutter?  

What tools do you need? I might not be understanding your question correctly, could you elaborate?

**Comment by NarHakobyan** [comment]
I found it, source_gen

**Comment by modulovalue** [comment]
I wrote the code by hand but I guess source_gen could be used too for some parts

**Comment by NarHakobyan** [comment]
Good thanks, it's someting new for me
